### ISSUE TITLE
Can't use DebugWriter from the command line

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#119]
```
$ bundle exec traject -w Traject::DebugWriter -c traject_config.rb adrl_etd_sample.mrc
2016-01-11T11:34:31-06:00  INFO traject (2.1.0) executing with: `-w Traject::DebugWriter -c traject_config.rb adrl_etd_sample.mrc`
2016-01-11T11:34:31-06:00  INFO Reading from adrl_etd_sample.mrc
2016-01-11T11:34:31-06:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NameError: uninitialized constant DebugWriter>
/Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/qualified_const_get.rb:37:in `const_get': uninitialized constant DebugWriter (NameError)
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/qualified_const_get.rb:37:in `block in qualified_const_get'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/qualified_const_get.rb:37:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/qualified_const_get.rb:37:in `inject'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/qualified_const_get.rb:37:in `qualified_const_get'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:501:in `writer!'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:506:in `writer'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:399:in `process'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/command_line.rb:67:in `execute'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/bin/traject:14:in `<top (required)>'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/traject:23:in `load'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/traject:23:in `<main>'
```

**Comment by billdueber** [comment]
Addressed by #121
