### ISSUE TITLE
Null pointer error in DebugWriter

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#120]
```
$ bundle exec traject --debug-mode -c traject_config.rb adrl_etd_sample.mrc
2016-01-11T11:36:39-06:00  INFO traject (2.1.0) executing with: `--debug-mode -c traject_config.rb adrl_etd_sample.mrc`
2016-01-11T11:36:39-06:00  INFO Reading from adrl_etd_sample.mrc
2016-01-11T11:36:39-06:00 DEBUG beginning Indexer#process with settings: {"writer_class_name"=>"Traject::DebugWriter", "log.level"=>"debug", "processing_thread_pool"=>0, "solr.url"=>"http://solr.somewhere.edu:8983/solr/corename", "command_line.filename"=>"adrl_etd_sample.mrc", "reader_class_name"=>"Traject::MarcReader", "marc_source.type"=>"binary", "solrj_writer.batch_size"=>200, "solrj_writer.thread_pool"=>1, "log.batch_size.severity"=>"info"}
2016-01-11T11:36:39-06:00  INFO    Indexer with 0 processing threads, reader: Traject::MarcReader and writer: Traject::DebugWriter
2016-01-11T11:36:39-06:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NoMethodError: undefined method `first' for nil:NilClass>
/Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/debug_writer.rb:42:in `block in serialize': undefined method `first' for nil:NilClass (NoMethodError)
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/debug_writer.rb:42:in `map'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/debug_writer.rb:42:in `serialize'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/line_writer.rb:39:in `put'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:438:in `block (2 levels) in process'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/thread_pool.rb:116:in `maybe_in_thread_pool'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:433:in `block in process'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/marc-1.0.0/lib/marc/reader.rb:234:in `block in each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/marc-1.0.0/lib/marc/reader.rb:273:in `each_raw'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/marc-1.0.0/lib/marc/reader.rb:232:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/marc_reader.rb:86:in `each'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/indexer.rb:403:in `process'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/lib/traject/command_line.rb:67:in `execute'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/traject-2.1.0/bin/traject:14:in `<top (required)>'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/traject:23:in `load'
	from /Users/justin/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/traject:23:in `<main>'
```

**Comment by billdueber** [comment]
Addressed by #121
