### ISSUE TITLE
Running traject in an activejob can lock up forever

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#142]
When using the `:inline` activejob adapter
```
2017-08-18T12:02:42-05:00  INFO    Indexer with 1 processing threads, reader: XmlReader and writer: DlmeJsonResourceWriter
^C/Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `sleep': Interrupt
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `wait'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:43:in `ns_wait'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/abstract_lockable_object.rb:43:in `ns_wait_until'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/event.rb:87:in `block in wait'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/atomic/event.rb:84:in `wait'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_executor_service.rb:49:in `wait_for_termination'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/traject-2.3.3/lib/traject/thread_pool.rb:154:in `shutdown_and_wait'
	from /Users/jcoyne/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/traject-2.3.3/lib/traject/indexer.rb:487:in `process'
	from /Users/jcoyne/workspace/dlss/dlme/app/jobs/tei_transform_job.rb:11:in `perform'
```

**Comment by jrochkind** [comment]
What version of Rails please? Rails did some crazy things in... I forget if it's 5.0 or 5.1 that theoretically improve the concurrency story, but make it a lot harder to work with. https://github.com/ruby-concurrency/concurrent-ruby/issues/585

**Comment by jrochkind** [comment]
Could you try turning on eager_loading in your rails config and see if it still locks up? I am not necessarily suggesting that as a solution, but it will help diagnose the problem if eager loading being on and auto-loading being off solves it.

**Comment by jrochkind** [comment]
You could also, assuming this is happening only in standard development-mode, and I'm on the right track for what's causing it, try wrapping your use of traject in:

   Rails.application.executor.wrap do
      # traject goes here
   end

Or you could try setting traject to not use any multi-threading, I forget how/what config might do that.

**Comment by jcoyne** [comment]
@jrochkind  Setting `config.eager_load = true` seems to fix the problem.  the `Rails.application.executor.wrap { ... }` doesn't seem to have any effect.

**Comment by jrochkind** [comment]
Cool, that does support my theory that it's the rails auto-loading stuff. There are ways around it other than giving up on auto-loading, but they require using a couple Rails methods. I think I was misremembering that `executor.wrap` alone is enough, you also need a `ActiveSupport::Dependencies.interlock.permit_concurrent_loads` somewhere maybe -- possibly somewhere inside Traject's implementation, alas. Please see discussion at https://github.com/ruby-concurrency/concurrent-ruby/issues/585

I'm not sure what traject can do here. Perhaps traject, in the presence of Rails, should use the Rails API inside it's own code to have it's concurrency work well with Rails autoload?  Traject currently doesn't depend on Rails, and I wouldn't want to add it as a gemspec dependency, but it could still call Rails API in the presence of Rails. It could automatically detect the presence of rails with `defined? Rails` and inspecting `Rails::Version`. Or it could just be a manual traject config `use_rails5_concurrency_api` or something. 

Not entirely happy with any of those solutions. The Rails5 autoload concurrency architecture means anything doing multi-threaded concurrency, in a Rails app with auto-loading on (ie eager-loading off) needs to use the Rails API.  Which is problematic for gems that aren't meant to depend on Rails.  There is some discussion of the unhappy situation, but no great solutions, at the thread linked above.

**Comment by jrochkind** [comment]
the `bento_search` gem already depends on Rails. I made it compatible with Rails5 auto-loading by detecting Rails version (or, actually, feature sniffing, it looks like), and having it call `permit_concurrent_loads!` and `executor.wrap` at the right place if they are available. 

https://github.com/jrochkind/bento_search/blob/b6b75e80ff1d74e0562d4b293feb9fc279615ab5/app/models/bento_search/concurrent_searcher.rb#L106-L129

**Comment by jrochkind** [comment]
Also, just to be clear with the exact traject API:  If you turn off concurrency in traject, it should no longer have a problem with Rails5 auto-loading. 

I _think_ you can turn off all concurrency by setting the configuration settings. `processing_thread_pool` to 0.  If your writer uses concurrency, you have to turn this off too, for instance  `solr_writer.thread_pool` to 0. 

I think that would do it, but am not completely sure. If the path of turning off concurrency entirely in order to work with Rails autoloading is interesting to anyone, perhaps we should provide a single global setting that ensures _no concurrency anywhere_ for environments where it causes problems.

**Comment by billdueber** [comment]
That's correct -- you currently need to set each thread pool (processing / writing) to zero individually. Would probably be a good idea to have that switch.

**Comment by jrochkind** [comment]
This isn't exactly traject's fault, it's Rails fault -- _anything_ that does ordinary use of threads will now cause deadlock if used in Rails auto-loading _and_ an auto-load is actually triggered.  Unless it uses Rails-specific API. Lots of people are trying to figure out how to deal with this, and getting frustrated. I don't think any great patterns have emerged. 

I think for jcoyne's case turning off auto-loading works fine and is not that inconvenient, so we're okay for now?

**Comment by billdueber** [comment]
I think we're good, although I don't know enough about autoloading to really understand what we're talking about. Can one of you put up a ticket that says, 'Hey. Do <this>'?

**Comment by jrochkind** [comment]
Not sure if you hit submit before you were ready, but It is unclear to me what to do. I think if you read ruby-concurrency/concurrent-ruby#585, you'll have some background.
