### ISSUE TITLE
But in DebugWriter when Encoding.default_external is not UTF-8?

### ISSUE THREAD

**Issue by jrochkind** [traject/traject#189]
@ruthbrarian on Slack reported trying to use traject on windows, encountered a bug. Stack trace shows it's an encoding problem, specifically from the DebugWriter, which seems to occur when Encoding.default_external is something other than UTF-8 (as it generally is on ruby Windows). 

```
2018-08-08T12:15:05-04:00  INFO ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
2018-08-08T12:15:05-04:00  INFO traject (2.3.4) executing with: `--debug-mode -c psulib_config.rb sample_psucat_marc.mrc`
2018-08-08T12:15:05-04:00  INFO Reading from sample_psucat_marc.mrc
2018-08-08T12:15:05-04:00 DEBUG beginning Indexer#process with settings: {"writer_class_name"=>"Traject::DebugWriter", "log.level"=>"debug", "processing_thread_pool"=>0, "solr.url"=>"http://localhost:8983/solr/blacklight-core", "log.batch_size"=>10000, "command_line.filename"=>"sample_psucat_marc.mrc", "reader_class_name"=>"Traject::MarcReader", "marc_source.type"=>"binary", "solr_writer.batch_size"=>100, "solr_writer.thread_pool"=>1, "log.batch_size.severity"=>"info", "allow_nil_values"=>false, "allow_duplicate_values"=>true, "allow_empty_fields"=>false}
2018-08-08T12:15:05-04:00  INFO    Indexer with 0 processing threads, reader: Traject::MarcReader and writer: Traject::DebugWriter
2018-08-08T12:15:05-04:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8>
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/debug_writer.rb:70:in `join': incompatible character encodings: IBM437 and UTF-8 (Encoding::CompatibilityError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/debug_writer.rb:70:in `serialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/line_writer.rb:39:in `put'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/indexer.rb:444:in `block (2 levels) in process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/thread_pool.rb:116:in `maybe_in_thread_pool'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/indexer.rb:439:in `block in process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/marc-1.0.2/lib/marc/reader.rb:234:in `block in each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/marc-1.0.2/lib/marc/reader.rb:273:in `each_raw'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/marc-1.0.2/lib/marc/reader.rb:232:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/marc_reader.rb:86:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/indexer.rb:409:in `process'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/lib/traject/command_line.rb:67:in `execute'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/traject-2.3.4/bin/traject:14:in `<top (required)>'
        from C:/Ruby24-x64/bin/traject:23:in `load'
        from C:/Ruby24-x64/bin/traject:23:in `<main>'
```

**Comment by jrochkind** [comment]
Did reproduce with a MARC and config file shared by @ruthbrarian. Can't share the MARC file publicly here though, on to figure out what's causing it.

**Comment by jrochkind** [comment]
Weird. The values extracted from the MARC record are coming back as Encoding.default_external. 

This may actually be the documented/intended behavior for ruby-marc? 

Ah wait, i did find this in traject docs:

```
# * "marc_source.encoding": Only used for marc_source.type 'binary', character encoding
#         of the source marc records. Can be any
#         encoding recognized by ruby, OR 'MARC-8'.  For 'MARC-8', content will
#         be transcoded (by ruby-marc) to UTF-8 in internal MARC::Record Strings. 
#         Default nil, meaning let MARC::Reader use it's default, which will
#         probably be Encoding.default_internal, which will probably be UTF-8. 
#         Right now Traject::MarcReader is hard-coded to transcode to UTF-8 as
#         an internal encoding. 
```

But that suggests it would be `Encoding.default_internal` not `default_external`, and also suggests "Right now Traject::MarcReader is hard-coded to transcode to UTF-8 as  an internal encoding", which is what is not happening I think. 

Encodings, always brain twisting!

**Comment by jrochkind** [comment]
OK, this is super confusing as encoding things always are, but I think I've figured it out. 

@ruthtillman's sample file is MARC records in UTF-8. 

ruby-marc does _not_ use the the MARC encoding fixed byte to determine encoding (it's often wrong, but for better or worse it does not have that capability).  If no encoding is passed to it, it assumes `Encoding.default_external`.   (The traject doc's saying it used `Encoding.default_internal` were wrong). 

If you set the traject setting `marc_source.encoding` (generally either to `UTF-8` or `MARC-8`, that will be passed to ruby-marc.  But ruth's config this wasn't set, so ruby-marc will use it's default behavior, which is to figure the encoding of the marc file was `Encoding.default_external`. 

Which on Linux or MacOS systems is usually UTF-8, so it's right for Ruth's files in that case. 

On Windows, `Encoding.default_external` is often something else, like IBM437.  

* As an aside, U.S. Marc21 records can, I think _only_ be in UTF-8 or MARC-8 encodings, so I'm not sure it makes any sense for it to use Encoding.default_external when it's something else. But perhaps ruby-marc can be used with international MARC formats other than Marc21, so this may make sense. 

So on Windows, right away ruby-marc has read in strings that were _actually_ in UTF-8, but tagged them in ruby as IBM437. 

The traject docs _say_ "Traject::MarcReader is hard-coded to transcode to UTF-8 as an internal encoding.", but this was wrong, it wasn't doing that. 

* side note again: we should maybe fix it so it _is_ doing that?  And Traject 3.0 release would be a good time to do that. That would simply require passing changing MARCReader to pass kw arg `internal_encoding: "UTF-8"` to MARC::Reader.new, [here](https://github.com/traject/traject/blob/5754e3c0c207d461ca3a98728f7e1e7cf4ebbece/lib/traject/marc_reader.rb#L79.
   * If we make that change, then in Ruth's original case, no exception is raised, _but_ you have some corrupted strings. What should have been "précédé de L'original de Laura" becomes corrupted to "pr├⌐c├⌐d├⌐ de L'original de Laura"
   * In other cases, it might actually raise, so perhaps if we make the change to pass `internal_encoding: "UTF-8"` to Marc::Reader.new (so it behaves as was documented already), we should also pass `invalid: replace`, which MARC::Reader also respects. (MARC::Reader does not currently allow you to pass an `undef` arg, for undefined transcodes, as in [ruby #encode method](https://ruby-doc.org/core-1.9.3/String.html#method-i-encode). (MARC::Reader does have a `validate_encoding: true` to get fast raises, not sure if that's of interest here ). 

The "correct" way for Ruth to fix her problem is just to add:

```ruby
settings do
   settings do
     provide "marc_source.encoding", "UTF-8"
   end
end
```

Now regardless of what platform you are on, ruby-marc knows the MARC input is UTF-8, and all is well, and uncorrupted. 

However, there are still arguably bugs in traject, it could be responding _better_ to this error of wrong encoding. Either as above, with it not transcoding to UTF-8 as documented, and/or:

* DebugWriter should perhaps not assume everything in the output is UTF-8, and it should transcode to UTF-8 before trying to output to screen. The particular error Ruth got was from some of the output_hash being tagged IBM437 (although actually being invalid bytes for it!), and trying to combine it with UTF-8 strings for output to console (Is console even necessarily UTF-8? I have no idea!). 

Phew, encodings!

I am inclined to think maybe we should fix MarcReader to insist on transcoding everything to UTF-8... but really it hardly will come up, unless there are international users using encodings other than MARC8 and UTF8.  Cause UTF8 is already UTF8, and ruby-marc insists on transcoding MARC-8 to UTF-8 _also_ (since ruby doesn't know MARC-8). 

But if it will hardly come up, maybe that means might as well fix it, since it probably won't cause any problems either? :) Not sure!

**Comment by jrochkind** [comment]
Actually correcting the behavior to match pre-existing docs "Right now Traject::MarcReader is hard-coded to transcode to UTF-8 as an internal encoding" may have perf implications, so I'm inclined to do nothing maybe. 

Maybe remove the comment-doc that suggests wrongly?

**Comment by jrochkind** [comment]
Would love to get your code review and sign-off on this before merging @billdueber , if you have time!
